print('Арифметические действия')
print('2 + 2', end=' = ')
print(2 + 2)
print()

print('Получить тип данных')
print('type(2 + 2)', end=' = ')
print(type(2 + 2))
print("type('Hello World')", end=' = ')
print(type('Hello World'))
print('type(2 / 3)', end=' = ')
print(type(2 / 3))
print()

print('Целочисленное деление')
print('2 // 3', end=' = ')
print(2 // 3)
print('4 // 3', end=' = ')
print(4 // 3)
print('2 // 2', end=' = ')
print(2 // 2)
print('8 // 2', end=' = ')
print(8 // 2)
print()

print('Остаток от целочисленного деление / Взятие остатка / По модулю')
print('2 % 2', end=' = ')
print(2 % 2)
print('3 % 2', end=' = ')
print(3 % 2)
print('2 % 3', end=' = ')
print(2 % 3)
print('2 % 5', end=' = ')
print(2 % 5)
print()

print('Возведение в степень')
print('2 ** 3', end=' = ')
print(2 ** 3)
print()

print('Пример преобразования типа данных')
print("s = str(2 + 2) * int('2' + '2')", end=' = ')
s = str(2 + 2) * int('2' + '2')
print(s)
print()

print('Вывод длины переменной')
print("len(s)", end=(' = '))
print(len(s))
print()

print('Булевы значения:')
print('bool(0)', ' = ', bool(0))
print("bool('')", ' = ', bool(''))
print('bool(1)', ' = ', bool(1))
print('bool(-5)', ' = ', bool(5))
print("bool('Hello World')", ' = ', bool('Hello World'))
print()

print('Перевод строки символом \\n')
print('Hello \nWorld')
print()

print('Табуляция \\t')
print('Hello \tWorld')
print()

print('Экранирование кавычек \\')
print('Hello \'World\'')
print()

print('Разделители print')
print("sep='' " + '5', '10', '53', sep='')
print("sep='=' " + '5', '10', '53', sep='=')
print("sep=':' " + '5', '10', '53', sep=':')
print("sep=' ' " + '5', '10', '53', sep=' ')
print("sep='-' " + '5', '10', '53', sep='-')
print()

print('Форматная строка')
print('x = 5; y = 10; z = 53; w = 89')
x = 5; y = 10; z = 53; w = 89
print("'{}{}{}'.format(x, y, z) =", '{}{}{}'.format(x, y, z))
print("{:02}:{:02}:{:02}:{:03}'.format(x, y, z, w) =", '{:02}:{:02}:{:02}:{:03}'.format(x, y, z, w))
print()

print('Ввод данных')
print('name = input()')
# name = input()